routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
 /*
 *------------FrontEnd Router
 */
	Route::group(['namespace' => 'NewsBlog'], function () 
	{
		Route::get('/', 'BlogNews@index')
			->name('blog.news.index');
		Route::group(['prefix' => 'news'], function () 
		{
			Route::get('one/{id}', 'BlogNews@showOne')
				->name('blog.news.showone');
			Route::post('one/{id}', 'BlogNews@addComment')
				->name('blog.news.addComm');
			
			/*---------For users was authentication*-------------*/
			Route::group(['middleware'=>'auth'], function()
			{
				Route::get('add', 'BlogNews@addPostGet')
					->name('blog.news.addPostGet');
				Route::post('add', 'BlogNews@addPost')
					->name('blog.news.addPost');
				Route::get('edit/{id}', 'BlogNews@editPostGet')
					->name('blog.news.editPostGet');
				Route::post('edit/{id}', 'BlogNews@editPost')
					->name('blog.news.editPost');
				Route::get('delete/{id}', 'BlogNews@delPost')
					->name('blog.news.delPost');
				
			});
		});
		
		/*------For user authentication-------------*/
		Route::group(['prefix' => 'auth'], function ()
		{
			Route::get('login', 'BlogAuth@loginGet')
				->name('blog.auth.loginGet');
			Route::post('login', 'BlogAuth@loginPost')
				->name('blog.auth.loginPost');
			Route::get('registr', 'BlogAuth@registrGet')
				->name('blog.auth.registrGet');
			Route::post('registr', 'BlogAuth@registrPost')
				->name('blog.auth.registrPost');
			Route::get('logout', 'BlogAuth@logout')
				->name('blog.auth.logout');
		});
			
	});
/*
*------------------Admin Routes
*/
	Route::group(['namespace' => 'AdminBlog', 'prefix'=>'admin'], function () 
	{
		Route::get('/', 'AdminAuth@index');
		Route::post('/', 'AdminAuth@auth');
	});	 
	 
	 
	 
	 
	 
	 

app/Http/Controllers/NewsBlog/BlogNews.php
<?php
namespace App\Http\Controllers\NewsBlog;

use Illuminate\Http\Request;
use App\Http\Controllers\Blog; 
use App\Models\Post, App\Models\Comment, App\Models\User;
use App\Http\Requests\ValidBlog;
use Illuminate\Support\Facades\Auth;


class BlogNews extends Blog
{
	
	public function index()
	{
		$posts=Post::with('user')->withCount('comments')->paginate(2);
		if($posts->currentPage() > $posts->lastPage())
		{
			abort(404);
		}
		 
		$favPosts=Post::favorite(); /*added scopeFavorite*/
				
		return view('layouts.tmpltForTwo', [
						'page'=>'frontend.main',
						'title'=>'Главная',
						'posts' =>$posts,
						'favPosts'=>$favPosts,
						
				]);
				
	}
	
	public function showOne($id)
	{
		$post=Post::withCount('comments')/*added virtual colum {relation}_count*/
					->with('comments','comments.user')
					->findOrFail($id);
		
		return view('layouts.columOne', [
					'page'=>'frontend.article',
					'title'=>'Пост',
					'item'=>$post,
		]);
	}
	
	public function addComment(ValidBlog $request, $id)
	{
		/*  $this->validate($request, [
			'comment'=>'required',
      ]); */
		
		$post=Post::findOrFail($id);
		$post->comments()
			  ->create([
					'comment'=>$request->input('comment'),
					'user_id'=>$request->user()->id,
				]);
			
		return redirect()
				->route('blog.news.showone', ['id'=>$id]);
	}
	
	public function addPostGet()
	{
		$this->authorize('create', Post::class);
		
		
		return view('layouts.columOne', [
					'page'=>'frontend.addArticle',
					'title'=>'Добавление поста',
		]);
		
	}
	
	public function addPost(ValidBlog $request)
	{
		$this->authorize('create', Post::class);
		
		/* $this->validate($request, [
			'titlePost'=>'required|max:255',
			'post'=> 'required',
      ]); */
		
		/* $faker = Faker\Factory::create('ru_RU'); // create a Russian faker */
		
		Post::create([
			'is_active'=>1,
			'user_id'=> $request->user()->id,
			'post_title'=>$request->input('titlePost'),
			'post'=>$request->input('post'),
			/* 'image'=> $faker->imageUrl(640, 480), */
			'author'=>$request->user()->name,
		]);
		
		return redirect()
				->route('blog.news.index');
	}
	
	public function editPostGet(Post $post, $id)
	{
		$post=Post::findOrFail($id);
		
		$this->authorize('update', $post);
		
		return view('layouts.columOne', [
					'page'=>'frontend.editArticle',
					'title'=>'Редактирование поста',
					'post'=>$post,
		]);
	}
	
	public function editPost(ValidBlog $request, $id)
	{
		$post=Post::findOrFail($id);
		$this->authorize('update', $post);
		
		/* $this->validate($request, [
			'post_title'=>'required|max:255',
			'post'=> 'required',
      ]); */
		
		$post->fill($request->all());
		$post->save();
		
		return back();
	}
	
	public function delPost($id)
	{
		$post=Post::findOrFail($id);
		
		$this->authorize('delete', $post);
		$post->delete();
		
		return redirect()
				->route('blog.news.index');
	}
}

resources/views/traits/comments.blade.php
<div class="comments">
	
	@forelse ($item->comments as $comment)
	
	@if(!$comment->is_valid)
	<!-- Comment February 20, 2009 04:33-->
		<div class="comment">

			<div class="comm_hdr">
				<p>{{ $comment->user->name}} <span> | {{ $comment->created_at}}</span></p>
			</div>

			<div class="avat">
				<img src="../../images/avatar.jpg" alt="avatar" />
			</div>
		
			<p class="comm_txt">
			{{$comment->comment}}
			</p>

		</div>
	@endif
	@empty
		<p class="comm_txt">Нет коментарий для отображения</p>
	@endforelse

</div>

resources/views/traits/copyright.blade.php
<p>&copy;2016 blogair. All rights reserved. </p>

resources/views/traits/footerMenu.blade.php
<!-- Footer Menu -->
<div id="foo_menu">

	<a href="{{ route('blog.news.index') }}">Домашняя</a><span>.</span>
	<a href="{{ route('blog.auth.registrGet') }}">Регистрация</a><span>.</span>
	@can('create', App\Models\Post::class)
	<a href="{{ route('blog.news.addPostGet') }}">Добавить статью</a><span>.</span>
	@endcan
	<a href="#">О нас</a><span>.</span>
	<a href="#">Контакты</a>
	
</div>

resources/views/traits/mainCont.blade.php
@forelse ($posts as $post)
	<!-- Post -->
	<div class="post">
		
				
			<!-- Post Details -->
			<div class="post_inf">
				<span>{{$post->created_at}}</span><br />
				<span class="posn">{{$post->user->name}}</span><br />
				<a class="posc" href="{{ route('blog.news.showone',['id' => $post->id]) }}">
					коментарий {{$post->comments_count}}
				</a>
			</div>

			<!-- Post Title - Permalink -->
			<h1>
				<a href="{{ route('blog.news.showone',['id' => $post->id] ) }}">{{$post->post_title}}</a>
			</h1>
			
			<!-- Post Content -->
			<a class="pic_lnk" href="{{ route('blog.news.showone',['id' => $post->id] ) }}">
				<img height="300" src="{{$post->image}}" alt="post_pic{{$post->id}}" />
			</a>
			
			<p>{{$post->post}}</p>
			<p>
				@can('update', $post)
				<a class="link_auth" href="{{ route('blog.news.editPostGet',['id' => $post->id] ) }}">
					Редактировать статью
				</a>
				@endcan
				@can('delete', $post)
				<a class="link_auth"  href="{{ route('blog.news.delPost',['id' => $post->id] ) }}">
					Удалить статью
				</a>
				@endcan
			</p>
	</div>
@empty
    <h3><p class="post">Нет доступных постов для отображеня</p></h3>
@endforelse

resources/views/traits/mainMenu.blade.php
	     <!-- Logo -->
			<div id="logo">
				<a href="{{ route('blog.news.index') }}"></a>
			</div>

			<!-- Main Menu -->
			<div id="menu">
				<a class="mh" href="{{ route('blog.news.index') }}">Домашняя</a>
				<a class="mt" href="{{ route('blog.auth.registrGet') }}">Регистрация</a>
				@can('create', App\Models\Post::class)
				<a class="mw" href="{{ route('blog.news.addPostGet') }}">Добавить<br>статью</a>
				@endcan
			</div>

resources/views/traits/pagination.blade.php
{{ $posts->links() }}
<br><br>

resources/views/traits/post.blade.php
<!-- Post -->
	<div class="post">

		<!-- Post Details -->
		<div class="post_inf">

			<span>{{$item->created_at}}</span><br />
			<span class="posn">{{$item->user->name}}</span><br />
			<span class="posc">
				{{$item->comments_count}} Comments
			</span>

		</div>

		<!-- Post Title - Permalink -->
		<h1>
			<a href="#">{{$item->post_title}}</a>
		</h1>
		
		<a class="pic_lnk" href="#">
				<img src="{{$item->image}}" alt="post_pic{{$item->id}}" />
		</a>
		
		<!-- Post Content -->
		<p>
			{{$item->post}}
		</p>
		<p>
				@can('update', $item)
				<a class="link_auth" href="{{ route('blog.news.editPostGet',['id' => $item->id] ) }}">
					Редактировать статью
				</a>
				@endcan
				@can('delete', $item)
				<a class="link_auth"  href="{{ route('blog.news.delPost',['id' => $item->id] ) }}">
					Удалить статью
				</a>
				@endcan
			</p>

	</div>

resources/views/traits/topMenu.blade.php
	<!-- Top Menu -->
	<div id="hdl">
		<a href="#" class="hl">О нас</a>
		<a href="#" class="hl">Контакты</a>
		@if(Auth::check())
			<a href="{{ route('blog.auth.logout') }}" class="hl">
				Выход ({{ Auth::user()->name }})
			</a>
		@else
			<a href="{{ route('blog.auth.loginGet') }}" class="hl">Вход</a>
		@endif
		
	</div>